[project]
name = "efficient-sam3-tools"
version = "0.1.0"
requires-python = ">=3.10"

dependencies = [
    "torch",
    "onnx",
    "onnxconverter-common",
    "onnxruntime-gpu",
    "numpy>=2.2.6",
    "opencv-python>=4.11.0.86",
    "torchvision>=0.24.1",
    "timm>=1.0.17",
    "ftfy==6.1.1",
    "regex",
    "iopath>=0.1.10",
    "huggingface_hub",
    "tqdm",
    "einops",
    "psutil",
    "Pillow>=10.0.0",
]
